id: P009179
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W28739
  title: རྟ་མགྲིན་ཡང་ཕྱུང་ནག་པོའི་ལས་བྱང་ལག་ལེན་གྱི་རིམ་པ
  author: ''
  volumes:
    96c3c4dfcab647fa95aa910702b06083:
      image_group_id: I4637
      title: ''
      volume_number: 1
      total_pages: 318
      base_file: v001.txt
