id: I3349372C
legacy_id: P009179
ocr_import_info:
  bdrc_scan_id: W28739
  source: bdrc
  ocr_info:
    timestamp: '2020-03-22T17:17:10'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:37:35.223244+00:00'
last_modified: 2022-09-02 16:38:07.508364
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W28739
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW28739
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྟ་མགྲིན་ཡང་ཕྱུང་ནག་པོའི་ལས་བྱང་ལག་ལེན་གྱི་རིམ་པ།
statistics:
  ocr_word_mean_confidence_index: 0.8295134063536717
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I4637:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4637
      total_pages: 318
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I4637.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.8295134063536717
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
